config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "homes#top"
  get 'home/about' => "homes#about"
  resources :users, only: [:show, :edit, :index, :update]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name,
    length: { minimum: 2, maximum: 20 },
    uniqueness: true

  validates :introduction,
    length: { maximum: 50 }


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io:File.open(file_path),filename:'default-image.jpg',content_type:'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resources)
    user_path(current_user)
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to user_path(user.id)
    else
      render :new
    end
    
  end

  def edit
    user = User.new(user_params)
    if user.save
      redirect_to user_path(user.id)
    else
    render :new
    end
  end
  
  
  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new


  end

  def show
    @book= Book.find(params[:id])
    @user = User.find(@book.user_id)

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @books = Book.all
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end


  def index
    @user = current_user
    @users = User.all

  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <% if user.profile_image.attached? %>
    <%= image_tag user.get_profile_image(100,100) %>
    <% else %>
    <%= image_tag 'default-image', size: "100x100" %>
    <% end %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <a>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %> 
      <i class="fas fa-user-cog"></i>
      <% end %>
    </a>
  </div>
  <div class="row">
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book , url: books_path, method: :post do |book| %>
    <div class="form-group">
      <label class="book_title">Title</label>
      <%= book.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label class="book_opinion">Opinion</label>
      <%= book.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= book.submit "Create Book", class: "btn btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      <%= form_with model: @book, url: book_path(@book.id), method: :patch do |book| %>
      <div class="form-group">
        <label class="book_title">Title</label>
        <%= book.text_field :title, autofocus: true, id: "book_title", class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label class="book_opinion">Opinion</label>
        <%= book.text_area :body, autofocus: true, id: "book_body",class: "form-control book_body"  %>
      </div>
      <div class="form-group">
        <%= book.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to 'Show', book_path(@book.id) %>
      <a>|</a>
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="error_explanation">
  <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  </div>
  <div class="row">
    <%= render 'user_info', user: @user, book: @book  %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'user_info', user: @user, book: Book.new %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
         <tbody>
            <tr>
              <td>
                  <%= link_to user_path(@user.id) do %>
                  <%= image_tag @book.user.get_profile_image(100,100) %></br>
                  <%= @book.user.name %>
                  <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id), method: :get, class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers!</strong>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book"></i>
      <string>Bookers!!</string>
      </h1>
      <p>in
      <i class="fas fa-book"></i>
      Bookers,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" area-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link text-light" href= "/users/<%= current_user.id %>" >
                <i class="fas fa-home"></i>
                Home
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>
              Users
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>
              Books
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>
              Log out
              </a>
            </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link text-light" href= "/">
              <i class="fas fa-home"></i>
              Home
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href= "/home/about" >
              <i class="fas fa-link"></i>
              About
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href= "/users/sign_up" >
              <i class="fas fa-user-plus"></i>
              Sign up
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href= "/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>
              Log in
              </a>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <p class="notice">
    <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
    <% end %>
    </p>
      <%= yield %>
    </main>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
        <%= form_with model: @user, url: user_path(@user.id), method: :patch do  |user| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= user.text_field :name , class: "form-control name"%>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= user.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= user.text_area :introduction, class: "form-control introduction"%>
        </div>
        <div class="form-group">
          <%= user.submit 'Update User', class: "btn btn-secondary" %>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/user_info', user: @user, book: Book.new %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <tr>
            <th><%= image_tag user.get_profile_image(80,80) %></th>
            <th><%= user.name %></th>
            <th><%= link_to 'Show', user_path(user.id) %></th>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/user_info', user: @user, book: Book.new %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @books.each do |book| %>
            <% if book.user_id == @user.id %>
            <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
            <% end %>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>